if(Random==0){
global.RandomRememeber[0]=1;
room_goto(RM_MiniGameSniper)
}
if(Random==1){
global.RandomRememeber[1]=1;
room_goto(RM_MiniGameSheeps)
}
if(Random==2){
global.RandomRememeber[2]=1;
room_goto(RM_MiniGameMetronome)
}
if(Random==3){
global.RandomRememeber[3]=1;
room_goto(RM_MiniGameCook)
}
if(Random==4){
global.RandomRememeber[4]=1;
room_goto(RM_MiniGameBomb)
}
if(Random==5){
global.RandomRememeber[5]=1;
room_goto(RM_MiniGameBaldi)
}
